### ISSUE TITLE
support .emdaer directories that are not at the root of the repository

### ISSUE THREAD

**Issue by infiniteluke** [emdaer/emdaer#103]
Currently emdaer assumes you want to output READMEs to the root of your project. This is not always true in the case that some sub-directory of your project needs to be documented.

**Comment by infiniteluke** [comment]
work on this has begun at https://github.com/emdaer/emdaer/tree/regex-nested-paths but is incomplete

**Comment by flipactual** [comment]
I thought this was working? It _was_ working at some point

**Comment by infiniteluke** [comment]
I'm not sure. it may have been before things got rebased, but it looks like since we cut the beta it has not worked this way.

https://github.com/emdaer/emdaer/blob/001b54822926b1933f8a583f778664a587ff97e3/packages/cli/src/index.js#L17

This has been around for a while

**Comment by infiniteluke** [comment]
Also:
https://github.com/emdaer/emdaer/blob/001b54822926b1933f8a583f778664a587ff97e3/packages/cli/src/index.js#L29
has been around since beta, which outputs to root

**Comment by flipactual** [comment]
Oh maybe I'm misunderstanding... I believe `.emdaer/docs/foo.emdaer.md` still goes to `docs/foo.md`, no?

**Comment by infiniteluke** [comment]
correct. that works currently. so a work around to this issue would be to mirror your folder structure inside of `.emdaer` to get it to output to the right place. 

In my proposal, someone could just create a `.emdaer` in whatever directory they want and have it output to the adjacent directory. Or maybe we don't want that?

**Comment by flipactual** [comment]
I don't need that functionality. If you do, go for it

**Comment by flipactual** [comment]
Probably needs to be one or the other though – could have two templates for the same file

**Comment by infiniteluke** [comment]
can you expand on that?

**Comment by flipactual** [comment]
With existing functionality and the proposed additional functionality, `.emdaer/foo/bar.emdaer.md` and `foo/.emdaer/bar.emdaer.md` would write to the same location, no?

**Comment by infiniteluke** [comment]
correct, but now I'm waffling.. I feel like the current functionality is fine. It may be nice that all of your emdaer files are in the same place.

Maybe we let this lie for a while and simply document that if you need to nest a README inside your codebase you can mirror the directory structure inside `.emdaer`. Thoughts?

**Comment by flipactual** [comment]
I thought that was documented somewhere, but yeah, that is good for me
