### ISSUE TITLE
Document plugin usage

### ISSUE THREAD

**Issue by fluxsauce** [emdaer/emdaer#16]
For each plugin:

- How to install
- How to use
- Working example

Update main README to describe available plugins.

**Comment by flipactual** [comment]
https://github.com/emdaer/emdaer/issues/9 will help with linking to the specific packages – may adapt to be specifically for lerna monorepos

**Comment by flipactual** [comment]
`lerna exec` will help with running emdaer in each package – it should not be installed as a `devDependency` on any project

**Comment by flipactual** [comment]
And all packages should use the same template

**Comment by flipactual** [comment]
https://github.com/emdaer/emdaer/issues/2

**Comment by flipactual** [comment]
https://github.com/emdaer/emdaer/issues/25

**Comment by fluxsauce** [comment]
#32
