### ISSUE TITLE
Each plugin/transform should use itself as self-documentation

### ISSUE THREAD

**Issue by infiniteluke** [emdaer/emdaer#44]
## Problem description:
When visiting a plugin/transform on npm, an example should be shown in the readme. Other than the description, it is not obvious what each plugin/transform does. 

## Suggested solution:
It would be great if we could somehow get jsdoc's `@example` to do this for us. However, because of limitations with how plugins work currently (replace the emdaer comment inline) this may not be feasible until 2.0.

At a bare minimum this could be a process thing. If you're making a new plugin/transform. Demonstrate it in the respective readme and possible use it in the emdaer readme/contributing/etc.. if appropriate.

**Comment by flipactual** [comment]
This would be much simpler if we switched to AST parsing – a comment within a codeblock is not in fact a comment

The current behavior of processing those comments is not great

More on this soon

**Comment by flipactual** [comment]
@infiniteluke is this more viable now?

I think we should also have each README include our shields, a link to the monorepo, etc

**Comment by infiniteluke** [comment]
#92 is my proposed solution to this. It's still a partially manual process, but here's what it'd look like:

- New plugin/transform created in `src/index.js`
- Document the emdaer expression it enables as the first `@example` in the jsdoc block
```js
/**
 * Do a thing
 * @example
 * <!--emdaer-p
 *   - '@emdaer/plugin-my-plugin'
 *   - value: 'cool'
 * -->
 * @param                     options
 * @param   {string}          [options.value] The thing to do
 * @returns {Promise<string>} The thing
 */
async function myNewPlugin() {...}
```

- In the respective `README.emdaer.md`, use `@emdaer/plugin-jsdoc-tag-value` to pull the `example` tag from the jsdoc into the readme.
```md
<!--emdaer-p 
  - '@emdaer/plugin-jsdoc-tag-value'
  - source: ./src/index.js
    functionName: myNewPlugin
    tag: example
-->
```
