### ISSUE TITLE
Support templates

### ISSUE THREAD

**Issue by flipactual** [emdaer/emdaer#47]

**Comment by infiniteluke** [comment]
What if we described templates with JSON Schema (could still be written in yaml) and used https://github.com/epoberezkin/ajv to validate them? Each plugin could expose it's own schema, defining types, order, required etc.., and a template would just be a set of plugin schema refs.

This would allow us to eventually build something like https://atom.io/packages/linter-js-yaml.

This could be a good way to validate templates. I'm unsure what your ideas were for templates. Was it the ability to generate a boilerplate file?

**Comment by flipactual** [comment]
_canned_
