### ISSUE TITLE
%s/Readme/README/g

### ISSUE THREAD

**Issue by infiniteluke** [emdaer/emdaer#94]
lets standardize on "REAMDE"

---

_Other Owner's Note: definitely not a virus_

---

_Other Other Owner's Note: confirmed. it's legit_

**Comment by flipactual** [comment]
Read your comment ;)

**Comment by flipactual** [comment]
I'm a big fan of Neal Stephenson, but...

**Comment by infiniteluke** [comment]
> Read your comment ;)

I'm going to leave it. open source

**Comment by infiniteluke** [comment]
README. WE SHOULD STANDARDIZE ON README

**Comment by flipactual** [comment]
Alternative spellings of "README" are not tolerated in emdaer country

**Comment by infiniteluke** [comment]
I just did a search for this and found no instances of "readme" or "Readme"
